/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SectionPadding = {
  _type: "section-padding";
  top?: boolean;
  bottom?: boolean;
};

export type ButtonVariant =
  | "default"
  | "destructive"
  | "outline"
  | "secondary"
  | "ghost"
  | "link";

export type ColorVariant =
  | "background"
  | "primary"
  | "secondary"
  | "card"
  | "accent"
  | "destructive"
  | "muted";

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Link = {
  _type: "link";
  isExternal?: boolean;
  internalLink?: PageReference;
  title?: string;
  href?: string;
  target?: boolean;
  buttonVariant?: ButtonVariant;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        isExternal?: boolean;
        internalLink?: PageReference;
        href?: string;
        target?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | {
      videoId?: string;
      _type: "youtube";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
>;

export type DressCode = {
  _id: string;
  _type: "dressCode";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  description?: BlockContent;
  paletteColors?: Array<{
    colorKey?:
      | "deep-matcha"
      | "raspberry"
      | "golden-matcha"
      | "strawberry-jam"
      | "matcha-chiffon"
      | "berry-meringue"
      | "matcha-latte"
      | "strawberry-milk";
    colorLabel?: string;
    _key: string;
  }>;
  inspirationImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  additionalNotes?: string;
  publishedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type WeddingDetails = {
  _id: string;
  _type: "weddingDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ceremonyVenue?: string;
  ceremonyDate?: string;
  ceremonyTime?: string;
  ceremonyAddress?: string;
  ceremonyMapUrl?: string;
  receptionVenue?: string;
  receptionDate?: string;
  receptionTime?: string;
  receptionAddress?: string;
  receptionMapUrl?: string;
  publishedAt?: string;
};

export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  body?: BlockContent;
  publishedAt?: string;
  scheduledAt?: string;
};

export type GuestReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "guest";
};

export type Guest = {
  _id: string;
  _type: "guest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  slug?: Slug;
  plusOneEligible?: boolean;
  plusOneType?: "linked" | "open";
  plusOneLinkedGuest?: GuestReference;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type EntourageMember = {
  _id: string;
  _type: "entourageMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  colorAssignment?:
    | "deep-matcha"
    | "raspberry"
    | "golden-matcha"
    | "strawberry-jam"
    | "matcha-chiffon"
    | "berry-meringue"
    | "matcha-latte"
    | "strawberry-milk";
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  isPadrino?: boolean;
  orderRank?: string;
};

export type StoryChapter = {
  _id: string;
  _type: "storyChapter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  isProposal?: boolean;
  year?: number;
  caption?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  order?: number;
  orderRank?: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    dark?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    light?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    width?: number;
    height?: number;
  };
  siteName?: string;
  copyright?: BlockContent;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  body?: BlockContent;
  orderRank?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  blocks?: null;
  meta?: {
    title?: string;
    description?: string;
    noindex?: boolean;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  orderRank?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SectionPadding
  | ButtonVariant
  | ColorVariant
  | PageReference
  | Link
  | SanityImageAssetReference
  | BlockContent
  | DressCode
  | SanityImageCrop
  | SanityImageHotspot
  | WeddingDetails
  | Announcement
  | GuestReference
  | Guest
  | Slug
  | EntourageMember
  | StoryChapter
  | Settings
  | Navigation
  | Faq
  | Page
  | MediaTag
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../frontend/sanity/queries/announcements.ts
// Variable: ANNOUNCEMENTS_QUERY
// Query: *[_type == "announcement" && (scheduledAt == null || scheduledAt <= now())]    | order(publishedAt desc) {      _id,      title,      body,      publishedAt,      scheduledAt    }
export type ANNOUNCEMENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  body: BlockContent | null;
  publishedAt: string | null;
  scheduledAt: string | null;
}>;

// Source: ../frontend/sanity/queries/dressCode.ts
// Variable: DRESS_CODE_QUERY
// Query: *[_type == "dressCode"][0] {    label,    description,    paletteColors[] {      _key,      colorKey,      colorLabel    },    inspirationImages[] {      ...,      asset->{        _id,        url,        mimeType,        metadata {          lqip,          dimensions {            width,            height          }        }      }    },    additionalNotes  }
export type DRESS_CODE_QUERY_RESULT = {
  label: string | null;
  description: BlockContent | null;
  paletteColors: Array<{
    _key: string;
    colorKey:
      | "berry-meringue"
      | "deep-matcha"
      | "golden-matcha"
      | "matcha-chiffon"
      | "matcha-latte"
      | "raspberry"
      | "strawberry-jam"
      | "strawberry-milk"
      | null;
    colorLabel: string | null;
  }> | null;
  inspirationImages: Array<{
    asset: {
      _id: string;
      url: string | null;
      mimeType: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  additionalNotes: string | null;
} | null;

// Source: ../frontend/sanity/queries/entourage.ts
// Variable: PADRINOS_QUERY
// Query: *[_type == "entourageMember" && isPadrino == true] | order(orderRank asc, name asc) {    _id, name, role, colorAssignment,    photo {      ...,      alt,      asset->{        _id,        url,        mimeType,        metadata {          lqip,          dimensions { width, height }        }      }    }  }
export type PADRINOS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  colorAssignment:
    | "berry-meringue"
    | "deep-matcha"
    | "golden-matcha"
    | "matcha-chiffon"
    | "matcha-latte"
    | "raspberry"
    | "strawberry-jam"
    | "strawberry-milk"
    | null;
  photo: {
    asset: {
      _id: string;
      url: string | null;
      mimeType: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
}>;

// Source: ../frontend/sanity/queries/entourage.ts
// Variable: WEDDING_PARTY_QUERY
// Query: *[_type == "entourageMember" && isPadrino != true] | order(orderRank asc, role asc, name asc) {    _id, name, role, colorAssignment  }
export type WEDDING_PARTY_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  colorAssignment:
    | "berry-meringue"
    | "deep-matcha"
    | "golden-matcha"
    | "matcha-chiffon"
    | "matcha-latte"
    | "raspberry"
    | "strawberry-jam"
    | "strawberry-milk"
    | null;
}>;

// Source: ../frontend/sanity/queries/guests.ts
// Variable: GUEST_BY_SLUG_QUERY
// Query: *[_type == "guest" && slug.current == $slug][0] {    firstName,    "slug": slug.current,    plusOneEligible,    plusOneType,    plusOneLinkedGuest->{      firstName,      "slug": slug.current    }  }
export type GUEST_BY_SLUG_QUERY_RESULT = {
  firstName: string | null;
  slug: string | null;
  plusOneEligible: boolean | null;
  plusOneType: "linked" | "open" | null;
  plusOneLinkedGuest: {
    firstName: string | null;
    slug: string | null;
  } | null;
} | null;

// Source: ../frontend/sanity/queries/guests.ts
// Variable: ALL_GUEST_SLUGS_QUERY
// Query: *[_type == "guest" && defined(slug.current)] {    "slug": slug.current  }
export type ALL_GUEST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../frontend/sanity/queries/navigation.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"]{    _type,    _key,    links  }
export type NAVIGATION_QUERY_RESULT = Array<{
  _type: "navigation";
  _key: null;
  links: Array<
    {
      _key: string;
    } & Link
  > | null;
}>;

// Source: ../frontend/sanity/queries/page.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    blocks[]{      _type,      _key,    },      meta{    title,    description,    noindex,    image{        ...,  asset->{    _id,    url,    mimeType,    metadata {      lqip,      dimensions {        width,        height      }    }  }    }  },  }
export type PAGE_QUERY_RESULT = {
  blocks: null;
  meta: {
    title: string | null;
    description: string | null;
    noindex: boolean | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
        mimeType: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../frontend/sanity/queries/page.ts
// Variable: PAGES_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug)]{slug}
export type PAGES_SLUGS_QUERY_RESULT = Array<{
  slug: Slug;
}>;

// Source: ../frontend/sanity/queries/settings.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings"][0]{  _type,  siteName,  logo{    dark{      ...,      asset->{        _id,        url,        mimeType,        metadata {          lqip,          dimensions {            width,            height          }        }      }    },    light{      ...,      asset->{        _id,        url,        mimeType,        metadata {          lqip,          dimensions {            width,            height          }        }      }    },    width,    height,  },  copyright}
export type SETTINGS_QUERY_RESULT = {
  _type: "settings";
  siteName: string | null;
  logo: {
    dark: {
      asset: {
        _id: string;
        url: string | null;
        mimeType: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    light: {
      asset: {
        _id: string;
        url: string | null;
        mimeType: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    width: number | null;
    height: number | null;
  } | null;
  copyright: BlockContent | null;
} | null;

// Source: ../frontend/sanity/queries/storyChapters.ts
// Variable: STORY_CHAPTERS_QUERY
// Query: *[_type == "storyChapter" && isProposal != true] | order(order asc) {    _id,    year,    caption,    image {      ...,      asset->{        _id,        url,        mimeType,        metadata {          lqip,          dimensions {            width,            height          }        }      }    },    order,    publishedAt  }
export type STORY_CHAPTERS_QUERY_RESULT = Array<{
  _id: string;
  year: number | null;
  caption: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      mimeType: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  order: number | null;
  publishedAt: string | null;
}>;

// Source: ../frontend/sanity/queries/storyChapters.ts
// Variable: PROPOSAL_SECTION_QUERY
// Query: *[_type == "storyChapter" && isProposal == true][0] {    _id,    caption,    image {      ...,      asset->{        _id,        url,        mimeType,        metadata {          lqip,          dimensions {            width,            height          }        }      }    },    publishedAt  }
export type PROPOSAL_SECTION_QUERY_RESULT = {
  _id: string;
  caption: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      mimeType: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
} | null;

// Source: ../frontend/sanity/queries/weddingDetails.ts
// Variable: WEDDING_DETAILS_QUERY
// Query: *[_type == "weddingDetails"][0] {    ceremonyVenue,    ceremonyDate,    ceremonyTime,    ceremonyAddress,    ceremonyMapUrl,    receptionVenue,    receptionDate,    receptionTime,    receptionAddress,    receptionMapUrl  }
export type WEDDING_DETAILS_QUERY_RESULT = {
  ceremonyVenue: string | null;
  ceremonyDate: string | null;
  ceremonyTime: string | null;
  ceremonyAddress: string | null;
  ceremonyMapUrl: string | null;
  receptionVenue: string | null;
  receptionDate: string | null;
  receptionTime: string | null;
  receptionAddress: string | null;
  receptionMapUrl: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "announcement" && (scheduledAt == null || scheduledAt <= now())]\n    | order(publishedAt desc) {\n      _id,\n      title,\n      body,\n      publishedAt,\n      scheduledAt\n    }\n': ANNOUNCEMENTS_QUERY_RESULT;
    '\n  *[_type == "dressCode"][0] {\n    label,\n    description,\n    paletteColors[] {\n      _key,\n      colorKey,\n      colorLabel\n    },\n    inspirationImages[] {\n      ...,\n      asset->{\n        _id,\n        url,\n        mimeType,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height\n          }\n        }\n      }\n    },\n    additionalNotes\n  }\n': DRESS_CODE_QUERY_RESULT;
    '\n  *[_type == "entourageMember" && isPadrino == true] | order(orderRank asc, name asc) {\n    _id, name, role, colorAssignment,\n    photo {\n      ...,\n      alt,\n      asset->{\n        _id,\n        url,\n        mimeType,\n        metadata {\n          lqip,\n          dimensions { width, height }\n        }\n      }\n    }\n  }\n': PADRINOS_QUERY_RESULT;
    '\n  *[_type == "entourageMember" && isPadrino != true] | order(orderRank asc, role asc, name asc) {\n    _id, name, role, colorAssignment\n  }\n': WEDDING_PARTY_QUERY_RESULT;
    '\n  *[_type == "guest" && slug.current == $slug][0] {\n    firstName,\n    "slug": slug.current,\n    plusOneEligible,\n    plusOneType,\n    plusOneLinkedGuest->{\n      firstName,\n      "slug": slug.current\n    }\n  }\n': GUEST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "guest" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': ALL_GUEST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "navigation"]{\n    _type,\n    _key,\n    links\n  }\n': NAVIGATION_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    blocks[]{\n      _type,\n      _key,\n    },\n    \n  meta{\n    title,\n    description,\n    noindex,\n    image{\n      \n  ...,\n  asset->{\n    _id,\n    url,\n    mimeType,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height\n      }\n    }\n  }\n\n    }\n  }\n,\n  }\n': PAGE_QUERY_RESULT;
    '*[_type == "page" && defined(slug)]{slug}': PAGES_SLUGS_QUERY_RESULT;
    '*[_type == "settings"][0]{\n  _type,\n  siteName,\n  logo{\n    dark{\n      ...,\n      asset->{\n        _id,\n        url,\n        mimeType,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height\n          }\n        }\n      }\n    },\n    light{\n      ...,\n      asset->{\n        _id,\n        url,\n        mimeType,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height\n          }\n        }\n      }\n    },\n    width,\n    height,\n  },\n  copyright\n}': SETTINGS_QUERY_RESULT;
    '\n  *[_type == "storyChapter" && isProposal != true] | order(order asc) {\n    _id,\n    year,\n    caption,\n    image {\n      ...,\n      asset->{\n        _id,\n        url,\n        mimeType,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height\n          }\n        }\n      }\n    },\n    order,\n    publishedAt\n  }\n': STORY_CHAPTERS_QUERY_RESULT;
    '\n  *[_type == "storyChapter" && isProposal == true][0] {\n    _id,\n    caption,\n    image {\n      ...,\n      asset->{\n        _id,\n        url,\n        mimeType,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height\n          }\n        }\n      }\n    },\n    publishedAt\n  }\n': PROPOSAL_SECTION_QUERY_RESULT;
    '\n  *[_type == "weddingDetails"][0] {\n    ceremonyVenue,\n    ceremonyDate,\n    ceremonyTime,\n    ceremonyAddress,\n    ceremonyMapUrl,\n    receptionVenue,\n    receptionDate,\n    receptionTime,\n    receptionAddress,\n    receptionMapUrl\n  }\n': WEDDING_DETAILS_QUERY_RESULT;
  }
}
